### ISSUE TITLE
Create an Elasticsearch YAML file

### ISSUE THREAD

**Issue by SoyluAlaattin** [octoposprime/op-infra#16]
- The file name will be elasticsearch.
- Stating that Elasticsearch will consist of 3 replicas in the file.
- Specify in the file that Elasticsaerch will be included in the "octopos-prime-es" name space.
- Write the Elasticsaerch service to the same file.

**Comment by husamettinarabaci** [comment]
Please use only a short title and add the correct labels.

**Comment by husamettinarabaci** [comment]
The PR requires a review
