### ISSUE TITLE
Access of Remote Developers to the Project

### ISSUE THREAD

**Issue by SoyluAlaattin** [octoposprime/op-infra#17]
1. Create 3 services.
  - user:v1.0.0-dev   Port to use: 18081
  - logging:v1.0.0-dev   Port to use: 18082
  - graphql:v1.0.0-dev   Port to use: 18080
 Combine these 3 services under the "octopos-prime-dev" name space.

2.Under Default namespace for database access
  - Create "opdev" in postgres and connect it to port :5432
  - Create "db1" in redis and connect it to port :6379

**Comment by husamettinarabaci** [comment]
Please use only a short title and add the correct labels.
