### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by SoyluAlaattin** [octoposprime/op-infra#45]
Research MQTT

- What is MQTT?
- How to install MQTT?
- Learn the MQTT working logic.
- Research the use of MQTT with IoT devices.
- What is the relationship between MQTT and ChirpStack?
- Usage of MQTT with TTN.

Turn these researches into a document and add the codes used in these tols to the document.

**Comment by aybarsakbas** [comment]
The necessary research was done and documented.
