### ISSUE TITLE
Kubernetes Yaml Fields

### ISSUE THREAD

**Issue by SoyluAlaattin** [octoposprime/op-infra#46]
Research what the fields in the yaml file mean and what they are used for.

Example research fields:
- apiVersion
- kind
- image

Also search for the values ​​of the sample fields above:
- v1
- PersistentVolume
- postgres:13

Document this research.

**Comment by eneskesici** [comment]
Kubernetes yaml fields topic was researched and documentation was prepared for the Wiki.
